#!/usr/bin/env python3
"""
Convert binary file to Verilog $readmemh format (32-bit words).

Usage:
    python3 bin2hex32.py input.bin output.hex

This produces a hex file where each line is one 32-bit word,
suitable for loading with $readmemh into a 32-bit wide memory.
"""

import sys

def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    with open(input_file, 'rb') as f:
        data = f.read()
    
    # Pad to 4-byte boundary
    while len(data) % 4 != 0:
        data += b'\x00'
    
    with open(output_file, 'w') as f:
        f.write("// Firmware hex file (32-bit words, little-endian)\n")
        f.write("// Generated by bin2hex32.py\n")
        f.write("@00000000\n")  # Start at address 0
        
        for i in range(0, len(data), 4):
            # Little-endian: byte 0 is LSB
            word = (data[i+3] << 24) | (data[i+2] << 16) | (data[i+1] << 8) | data[i]
            f.write(f"{word:08X}\n")
    
    print(f"Converted {len(data)} bytes ({len(data)//4} words) to {output_file}")

if __name__ == "__main__":
    main()
