#!/usr/bin/env python3
"""
Convert Intel HEX or raw HEX file to Quartus MIF format.

Usage:
    python3 hex2mif.py input.hex output.mif [depth]

Arguments:
    input.hex  - Input file (Intel HEX or raw hex, one word per line)
    output.mif - Output MIF file for Quartus
    depth      - Memory depth in words (default: 16384 = 64KB/4)
"""

import sys
import os

def parse_intel_hex(filename):
    """Parse Intel HEX format file."""
    data = {}
    base_addr = 0
    
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or not line.startswith(':'):
                continue
            
            # Parse Intel HEX record
            byte_count = int(line[1:3], 16)
            address = int(line[3:7], 16)
            record_type = int(line[7:9], 16)
            
            if record_type == 0:  # Data record
                for i in range(byte_count):
                    byte_val = int(line[9 + i*2 : 11 + i*2], 16)
                    data[base_addr + address + i] = byte_val
            elif record_type == 2:  # Extended segment address
                base_addr = int(line[9:13], 16) << 4
            elif record_type == 4:  # Extended linear address
                base_addr = int(line[9:13], 16) << 16
            elif record_type == 1:  # EOF
                break
    
    return data

def parse_raw_hex(filename):
    """Parse raw hex file (one 32-bit word per line)."""
    data = {}
    addr = 0
    
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#') or line.startswith('//'):
                continue
            
            try:
                word = int(line, 16)
                # Store as little-endian bytes
                data[addr + 0] = (word >> 0) & 0xFF
                data[addr + 1] = (word >> 8) & 0xFF
                data[addr + 2] = (word >> 16) & 0xFF
                data[addr + 3] = (word >> 24) & 0xFF
                addr += 4
            except ValueError:
                continue
    
    return data

def parse_verilog_hex(filename):
    """Parse Verilog $readmemh format (objcopy -O verilog output)."""
    data = {}
    addr = 0
    
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            # Address line: @XXXXXXXX
            if line.startswith('@'):
                addr = int(line[1:], 16)
                continue
            
            # Data line: space-separated bytes
            bytes_str = line.split()
            for byte_str in bytes_str:
                try:
                    byte_val = int(byte_str, 16)
                    data[addr] = byte_val
                    addr += 1
                except ValueError:
                    continue
    
    return data

def bytes_to_words(data, depth):
    """Convert byte dictionary to word list."""
    words = [0] * depth
    
    for addr, byte_val in data.items():
        word_addr = addr // 4
        byte_idx = addr % 4
        
        if word_addr < depth:
            words[word_addr] |= byte_val << (byte_idx * 8)
    
    return words

def write_mif(words, filename):
    """Write Quartus MIF format file."""
    depth = len(words)
    
    with open(filename, 'w') as f:
        f.write("-- Quartus Memory Initialization File (.mif)\n")
        f.write("-- Generated by hex2mif.py\n")
        f.write("--\n\n")
        
        f.write(f"DEPTH = {depth};\n")
        f.write("WIDTH = 32;\n")
        f.write("ADDRESS_RADIX = HEX;\n")
        f.write("DATA_RADIX = HEX;\n\n")
        
        f.write("CONTENT BEGIN\n")
        
        # Find runs of zeros to compress output
        i = 0
        while i < depth:
            if words[i] == 0:
                # Find run of zeros
                j = i
                while j < depth and words[j] == 0:
                    j += 1
                
                if j - i > 1:
                    f.write(f"  [{i:04X}..{j-1:04X}] : 00000000;\n")
                else:
                    f.write(f"  {i:04X} : 00000000;\n")
                i = j
            else:
                f.write(f"  {i:04X} : {words[i]:08X};\n")
                i += 1
        
        f.write("END;\n")

def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    depth = int(sys.argv[3]) if len(sys.argv) > 3 else 16384
    
    # Detect input format
    with open(input_file, 'r') as f:
        first_line = f.readline().strip()
    
    if first_line.startswith(':'):
        print(f"Parsing Intel HEX: {input_file}")
        data = parse_intel_hex(input_file)
    elif first_line.startswith('@'):
        print(f"Parsing Verilog HEX: {input_file}")
        data = parse_verilog_hex(input_file)
    else:
        print(f"Parsing raw HEX: {input_file}")
        data = parse_raw_hex(input_file)
    
    # Convert to words
    words = bytes_to_words(data, depth)
    
    # Count non-zero words
    non_zero = sum(1 for w in words if w != 0)
    print(f"Loaded {non_zero} non-zero words")
    
    # Write MIF
    write_mif(words, output_file)
    print(f"Written: {output_file}")

if __name__ == "__main__":
    main()
